### PR TITLE
Get armor and weapon props working together

### PR DESCRIPTION
**Pull request by kingkaibr**
For this to work you should create panel pnlDefenceAttr and panel pnlOffenceAttr on statuswnd.frm and export the gui pack with the following attributes:

panel pnlDefenceAttr
		{
			x	= 300;
			y	= 96;
			width	= 17;
			height	= 17;
		}	
panel pnlOffenceAttr
		{
			x	= 320;
			y	= 96;
			width	= 17;
			height	= 17;
		}	
bellow is a vid from it working:
https://github.com/OpenDBO/OpenDBO-Core/assets/81758557/5c7284df-f4ac-4c7a-9809-a6de4aab3096

### CODE REVIEW

**Comment by SengokuNadeko** [comment]
Will review this when I get back home today 👍
For future reference, though, open a PR in the Assets repo as well if any update you make required modifying the games assets ^

**Comment by kingkaibr** [comment]
Sure, i will

**Comment by kingkaibr** [comment]
I did a little lint in one of the files and it made 1k changes, but the changes in the code itself were little, if its a problem i can just reimplement it

**Comment by SengokuNadeko** [comment]
> I did a little lint in one of the files and it made 1k changes, but the changes in the code itself were little, if its a problem i can just reimplement it

No no, just the gui file needs to be changed like you mentioned. It's no problem, I'll just do the changes and push it to the Assets repo

**Comment by kingkaibr** [comment]
Just wait till the rebase, i added things for another pr

**Comment by kingkaibr** [comment]
Done, u can mess with it

**Review by SengokuNadeko — APPROVED** [review]
Works nicely! Great work 👍

**Comment by kingkaibr** [comment]
When u could, do the merge so i can open another pr

**Comment by SengokuNadeko** [comment]
Oh my bad I thought I already merged it yesterday lol

**Comment by kingkaibr** [comment]
Theres is an issue related to this problem, maybe u can close that too

**Pull request merged**
