### PR TITLE
Add GM command to remove skills remaining cooldown time

### PR DESCRIPTION
**Pull request by ywwsshDBO**
Add GM command for remove remaining skills cooldown time. It's useful when you testing the skill.

### CODE REVIEW

**Review by SengokuNadeko — COMMENTED** [review]
What's the syntax for the command?

**Comment by ywwsshDBO** [comment]
it's "@removeskillscd". After you execute this command, you need relogin to game server for sync the skill cooldown time (just like "@warfog" command) because I cannot find a "GU" packet to sync the cooldown time to client.

**Comment by AKCore** [comment]
we had to add our own add our own packet to clear the player cache when doing stuff like warfog, removing skills, etc, Anything that is held in the cache handler that doesn't get updated on a login.

**Comment by SengokuNadeko** [comment]
Yeah, I think what @AKCore mentioned is probably the best way to do it. I'll merge this PR, but at some point, if you want to, you can add in some custom packets to make this gm command better ^

**Pull request merged**
